### ISSUE TITLE
你好，很感谢你的分享，但是没有04

### ISSUE THREAD

**Issue by everzeta** [tisu97/JAVASE_Notes#1]

**Comment by onetaker** [comment]
> 如果我没记错的话，04是IDEA的安装与使用

haha   强迫症想问一下01是什么呀

**Comment by everzeta** [comment]
> > 如果我没记错的话，04是IDEA的安装与使用
> 
> haha 强迫症想问一下01是什么呀

视频里是基础，java发展史之类的：https://www.bilibili.com/video/BV18J411W7cE，这个地址
